[package]
name = "AptosToken"
version = "1.0.0"

[addresses]
std = "0x1"
aptos_framework = "0x1"
aptos_token = "0x3"

[dependencies.MoveStdlib]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir= 'aptos-move/framework/move-stdlib'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir= 'aptos-move/framework/aptos-framework'